### ISSUE TITLE
BUG: 当重新打开Mindmap，形状发生了变化 

### ISSUE THREAD

**Issue by YIRU69** [Bowen-0x00/obsidian-excalidraw-plugin-ymjr#2]
![screenshots](https://github.com/Bowen-0x00/obsidian-excalidraw-plugin-ymjr/assets/48148292/74f42a0e-7441-44ac-b757-57608455348d)

**Comment by YIRU69** [comment]
如果子节点是大小差不多的还好，但是有差距很难看了，而且每一次都要调整，重新保存

**Comment by Bowen-0x00** [comment]
@YIRU69  你指的箭头的起点吗？

**Comment by YIRU69** [comment]
是的
