### ISSUE TITLE
利用思维导图脚本创建的画布，子节点和箭头不粘，直接就可以拿开，而我自己加的箭头却可以正常粘住

### ISSUE THREAD

**Issue by shoudeyunkaijianyueming** [Bowen-0x00/obsidian-excalidraw-plugin-ymjr#5]
https://github.com/Bowen-0x00/obsidian-excalidraw-plugin-ymjr/assets/71814666/5aa0d974-0eb1-4eed-9c21-306c3ee8bbe7

**Comment by shoudeyunkaijianyueming** [comment]
https://github.com/Bowen-0x00/obsidian-excalidraw-plugin-ymjr/assets/71814666/a413067e-4f14-4d97-b0c7-781291479497

**Comment by shoudeyunkaijianyueming** [comment]
https://github.com/Bowen-0x00/obsidian-excalidraw-plugin-ymjr/assets/71814666/91b06af4-f12e-4e9f-b7aa-cc1ecdb4c467

**Comment by shoudeyunkaijianyueming** [comment]
是我哪里设置不对，还是就是这么弄的，如果是这样弄的，我希望大佬能加上粘着的功能，要不挪挪位置块和箭头就乱了

**Comment by Bowen-0x00** [comment]
@shoudeyunkaijianyueming 是2.0.23-7解决重新打开思维导图箭头位置变化导致的问题。我重新想下解决方式。

**Comment by shoudeyunkaijianyueming** [comment]
好的，期待解决，谢谢您带来这么好的插件

**Comment by Bowen-0x00** [comment]
@shoudeyunkaijianyueming 你可以更新下插件和autorun-dragSelectedElementsHook这个脚本来试试新的拖拽效果

**Comment by shoudeyunkaijianyueming** [comment]
谢谢，问题已经解决
