### ISSUE TITLE
FR: 插件库更新中显示检查更新失败

### ISSUE THREAD

**Issue by YIRU69** [Bowen-0x00/obsidian-excalidraw-plugin-ymjr#7]
![image](https://github.com/Bowen-0x00/obsidian-excalidraw-plugin-ymjr/assets/48148292/567e3013-e056-48f8-9b70-7be9ad071594)

你好，这个问题是我在更新插件发现了，希望可以显示插件是否更新。谢谢

**Comment by Bowen-0x00** [comment]
@YIRU69 你好，更新下插件试下

**Comment by YIRU69** [comment]
可以了，非常感谢您。
