### ISSUE TITLE
FR: 增强 sticky note

### ISSUE THREAD

**Issue by YIRU69** [Bowen-0x00/obsidian-excalidraw-plugin-ymjr#8]
您好，可以考虑增强一下 sticky note 吗？或者增加一个脚本实现下面类似的功能。
![108533909-73b67200-72d1-11eb-85c9-d1a18948e852](https://github.com/Bowen-0x00/obsidian-excalidraw-plugin-ymjr/assets/48148292/51738ada-04c6-4412-9c29-c5178b22ced9)

**Comment by Bowen-0x00** [comment]
@YIRU69 这个目前有，无论是素材还是大叔作的脚本。你还可以增加阴影。我的示例库中还有callout

**Comment by YIRU69** [comment]
大叔的脚本我用过，所以叫增强，不过想想也能满足。另外问一下，如何加阴影呀。

**Comment by YIRU69** [comment]
@Bowen-0x00 我使用你的示例库文件进行学习，但是一直都无法做到像你的库文件一下

我都是直接使用 add shadow 进行添加阴影，但是效果很差，可以出个教程或者说明吗？谢谢
![image](https://github.com/Bowen-0x00/obsidian-excalidraw-plugin-ymjr/assets/48148292/4040345c-b7f9-495b-924e-ae853dee97e4)

**Comment by YIRU69** [comment]
好多的很好用，但是不知道怎么用。。

**Comment by Bowen-0x00** [comment]
@YIRU69 

add shadow脚本参数

"shadowColor": "-20",
"shadowBlur": "0.1",
"shadowOffsetX": "0.1",
"shadowOffsetY": "0.1"

参数1：阴影颜色，如果是数字的话代表着亮度增加/减少那么多；如果是#00FF00这种RGB十六进制的话就是指定的颜色
参数2、3、4：阴影模糊程度、偏移量，如果是数字的话代表相对于 元素的宽度*数字；如果是2px这种形式的话就是指定的绝对值

**Comment by YIRU69** [comment]
谢谢，学会了
