### ISSUE TITLE
FR: 图像对齐提示

### ISSUE THREAD

**Issue by YIRU69** [Bowen-0x00/obsidian-excalidraw-plugin-ymjr#9]
我在使用 excalidraw.com 的官方图时候发现有了图像对齐的提示，但是在插件中并没有，如图所示红色的提示
![image](https://github.com/Bowen-0x00/obsidian-excalidraw-plugin-ymjr/assets/48148292/ebbba671-f5f9-4c11-ac77-a2ff2e54462d)

**Comment by Bowen-0x00** [comment]
@YIRU69  😑
不开启grid的情况下按ctrl 拖动

**Comment by YIRU69** [comment]
哦哦，谢谢
